### ISSUE TITLE
Superfluous temporary files generated by PlotEnv class when performing more than one plot

### ISSUE THREAD

**Issue by mspraggs** [aportelli/LatAnalyze3#6]
To recreate, simply create and save two plots one after the other, resetting the plot environment in between with the `PlotEnv::reset` member function. Even if the save paths are different, the temporary text files (with the `.dat` extension) produced from the first plot are then saved again in the second plot save path, potentially wasting disk space.

This obviously isn't a showstopping bug, but I thought it was worth mentioning.

**Comment by aportelli** [comment]
Should be solved, do you confirm?

**Comment by mspraggs** [comment]
I will check later today :-)

**Comment by mspraggs** [comment]
Yep that fixed it, thanks!
