### ISSUE TITLE
Possible bug in StatArray::covariance?

### ISSUE THREAD

**Issue by mspraggs** [aportelli/LatAnalyze3#9]
I may be mistaken, but I think the formula for computing the variance in StatArray may be wrong. At StatArray.hpp:183, the sum of squared deviations from the mean is divided by N - 1, where N is the number of samples. Compare this to the formula given in Gattringer and Lang (page 97, equation 4.71), where the divisor is N. Is this an actual error, or are you trying to account for bias in some way?

**Comment by aportelli** [comment]
Hi Matt,
Thanks for having a look. Yes you got it is the unbiased estimate for the variance.
